server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'mayank28072001'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true